# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import byzantine_pb2 as byzantine__pb2


class ByzantineStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendDecision = channel.unary_unary(
                '/Byzantine/SendDecision',
                request_serializer=byzantine__pb2.Decision.SerializeToString,
                response_deserializer=byzantine__pb2.Acknowledge.FromString,
                )


class ByzantineServicer(object):
    """Missing associated documentation comment in .proto file"""

    def SendDecision(self, request, context):
        """A simple RPC

        To send the decision to the server

        Expects a Acknowledge reply
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ByzantineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.SendDecision,
                    request_deserializer=byzantine__pb2.Decision.FromString,
                    response_serializer=byzantine__pb2.Acknowledge.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Byzantine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Byzantine(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def SendDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Byzantine/SendDecision',
            byzantine__pb2.Decision.SerializeToString,
            byzantine__pb2.Acknowledge.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
