# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: byzantine.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='byzantine.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0f\x62yzantine.proto\">\n\x08\x44\x65\x63ision\x12\x17\n\x0f\x65ncoded_message\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\x02\x12\x0b\n\x03mac\x18\x03 \x01(\t\"\"\n\x0b\x41\x63knowledge\x12\x13\n\x0b\x61\x63knowledge\x18\x01 \x01(\x08\x32\x36\n\tByzantine\x12)\n\x0cSendDecision\x12\t.Decision\x1a\x0c.Acknowledge\"\x00\x62\x06proto3'
)




_DECISION = _descriptor.Descriptor(
  name='Decision',
  full_name='Decision',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='encoded_message', full_name='Decision.encoded_message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='Decision.time', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mac', full_name='Decision.mac', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=81,
)


_ACKNOWLEDGE = _descriptor.Descriptor(
  name='Acknowledge',
  full_name='Acknowledge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='acknowledge', full_name='Acknowledge.acknowledge', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=117,
)

DESCRIPTOR.message_types_by_name['Decision'] = _DECISION
DESCRIPTOR.message_types_by_name['Acknowledge'] = _ACKNOWLEDGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Decision = _reflection.GeneratedProtocolMessageType('Decision', (_message.Message,), {
  'DESCRIPTOR' : _DECISION,
  '__module__' : 'byzantine_pb2'
  # @@protoc_insertion_point(class_scope:Decision)
  })
_sym_db.RegisterMessage(Decision)

Acknowledge = _reflection.GeneratedProtocolMessageType('Acknowledge', (_message.Message,), {
  'DESCRIPTOR' : _ACKNOWLEDGE,
  '__module__' : 'byzantine_pb2'
  # @@protoc_insertion_point(class_scope:Acknowledge)
  })
_sym_db.RegisterMessage(Acknowledge)



_BYZANTINE = _descriptor.ServiceDescriptor(
  name='Byzantine',
  full_name='Byzantine',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=119,
  serialized_end=173,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendDecision',
    full_name='Byzantine.SendDecision',
    index=0,
    containing_service=None,
    input_type=_DECISION,
    output_type=_ACKNOWLEDGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BYZANTINE)

DESCRIPTOR.services_by_name['Byzantine'] = _BYZANTINE

# @@protoc_insertion_point(module_scope)
